namespace AiRTech.Core.Subjects
{
    public enum SubjectType
    {
        PODSTAWY_ELEKTRONIKI, PODSTAWY_TEORII_SYGNALOW, MECHANIKA, PODSTAWY_AUTOMATYKI, METODY_NUMERYCZNE, ANGIELSKI, ELEMENTY_OPTYKI_I_AKUSTYKI
    }
}