package eu.grmdev.airtech.server.dto;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lluka' at '11/26/16 8:11 PM' with Gradle 2.14.1
 *
 * @author lluka, @date 11/26/16 8:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
