import org.junit.Test;

import eu.grmdev.airtech.server.dto.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lluka' at '11/26/16 8:11 PM' with Gradle 2.14.1
 *
 * @author lluka, @date 11/26/16 8:11 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
